### PR TITLE
Clean up code for the Senior Seminars

### PR DESCRIPTION
**Pull request by emmasax1**
## What does this pull request do?
* Deleted the `README.MD` files in the senior seminar directories, since the code has started to use the `index.md` files
* Transferred over the gold stars from the `README.MD` files to the `index.md` files, consulting past email history announcing the gold star awards
* Transferred over the schedule, including dates/times/rooms, from the `README.MD` files to the `index.md` files
* Respaced `seminars.html` for easier reading

## How should I test this pull request before merging?
* Load the website locally:
  - [ ] The "All Seminars" page loads properly and pagination shows up properly
  - [ ] The "All Seminars" search box continues to function properly
  - [ ] Loading each semester's page continues to work
  * There should be new gold stars on the following pages:
    - [ ] Fall 2011
    - [ ] Fall 2012
    - [ ] Fall 2013
    - [ ] Fall 2014
    - [ ] Fall 2015
    - [ ] Fall 2016
    - [ ] Spring 2012
    - [ ] Spring 2014
    - [ ] Spring 2015
    - [ ] Spring 2016

### Thank you!

### CODE REVIEW

**Comment by emmasax1** [comment]
@elenam and @floogulinc:
Please look over this PR I made as you are able (I'm sure you're all quite busy!). Also, I'm unsure how to run this repo locally.... what system is it using? Grunt? Npm? Jekyll? @floogulinc, how do you run it locally?

Thank you!

**Comment by floogulinc** [comment]
To run locally, make sure you have Ruby installed and install Jekyll and Bundler with `gem install jekyll bundler`. Then run `bundle install` in the root directory of the repo. To start a local webserver that automatically rebuilds the site, run `bundle exec jekyll serve`.

**Comment by floogulinc** [comment]
The reason I had the pagination with `outerwindow` and `innerwindow` set to 1 was because any more and it starts to wrap to a new line on mobile like this:



I don't really like the pagination this library provides in general and wish it was just a next and previous page button.

**Comment by floogulinc** [comment]
The README files do have some information not preserved in the index.md files right now and that is the time each presentation took place. I don't know if that's too important but I was just keeping the README files for reference.

I've build the site and everything is working.

**Comment by emmasax1** [comment]
@floogulinc: I've moved over all of the rooms/dates/times from the Readme files to the index files, as well as I've added in all of the appropriate breaks in the schedules. I've also verified the page loads locally through `jeykll`. Please look over again.

**Comment by floogulinc** [comment]
Looks good to me, thanks!

I would be in favor of switching back the pagination settings so it looks better on mobile, I think it's adequate for the majority of users.

**Comment by emmasax1** [comment]
Sounds good!

**Comment by emmasax1** [comment]
@floogulinc Done!

**Comment by floogulinc** [comment]
Everything look good to you @elenam?

**Comment by elenam** [comment]
> To run locally, make sure you have Ruby installed and install Jekyll and Bundler with `gem install jekyll bundler` to install Jekyll and Bundler. Then run `bundle install` in the root directory of the repo. To start a local webserver that automatically rebuilds the site, run `bundle exec jekyll serve`. Then you should have it running at http://localhost:4000/

This should be in the README for the site.

**Comment by elenam** [comment]
Looks great to me! Thanks, @emmasax1 for adding the missing info and @floogulinc for help and clarifications!

**Comment by emmasax1** [comment]
@elenam @floogulinc It looks like the changes weren't pushed to the site. I believe the pull request has to be merged instead of closed. Could someone please reopen the PR and then press the green Merge button?

Thanks!

**Comment by floogulinc** [comment]
Yeah, @elenam probably hit "comment and close". I'll merge it.

**Comment by emmasax1** [comment]
Thank you!

**Comment by elenam** [comment]
Yeah, I was under the impression that I was closing the issue, not a PR. Apologies.

**Pull request merged**
